/* tslint:disable */
/* eslint-disable */
/**
 * AlexProof
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    CreateUser,
    CreateUserFromJSON,
    CreateUserToJSON,
    UserLogin,
    UserLoginFromJSON,
    UserLoginToJSON,
} from '../models';

export interface LoginCreateUserPostRequest {
    createUser?: CreateUser;
}

export interface LoginPostRequest {
    createUser?: CreateUser;
}

/**
 * 
 */
export class LoginApi extends runtime.BaseAPI {

    /**
     */
    async loginCreateUserPostRaw(requestParameters: LoginCreateUserPostRequest): Promise<runtime.ApiResponse<UserLogin>> {
        const queryParameters: runtime.HTTPQuery = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = typeof token === 'function' ? token("bearer", []) : token;

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/Login/createUser`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateUserToJSON(requestParameters.createUser),
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => UserLoginFromJSON(jsonValue));
    }

    /**
     */
    async loginCreateUserPost(requestParameters: LoginCreateUserPostRequest): Promise<UserLogin> {
        const response = await this.loginCreateUserPostRaw(requestParameters);
        return await response.value();
    }

    /**
     */
    async loginPostRaw(requestParameters: LoginPostRequest): Promise<runtime.ApiResponse<UserLogin>> {
        const queryParameters: runtime.HTTPQuery = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = typeof token === 'function' ? token("bearer", []) : token;

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/Login`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateUserToJSON(requestParameters.createUser),
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => UserLoginFromJSON(jsonValue));
    }

    /**
     */
    async loginPost(requestParameters: LoginPostRequest): Promise<UserLogin> {
        const response = await this.loginPostRaw(requestParameters);
        return await response.value();
    }

}
