/* tslint:disable */
/* eslint-disable */
/**
 * AlexProof
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    OrderType,
    OrderTypeFromJSON,
    OrderTypeFromJSONTyped,
    OrderTypeToJSON,
} from './';

/**
 * 
 * @export
 * @interface FindOrders
 */
export interface FindOrders {
    /**
     * 
     * @type {OrderType}
     * @memberof FindOrders
     */
    orderType?: OrderType;
    /**
     * 
     * @type {number}
     * @memberof FindOrders
     */
    page?: number;
    /**
     * 
     * @type {number}
     * @memberof FindOrders
     */
    pageSize?: number;
}

export function FindOrdersFromJSON(json: any): FindOrders {
    return FindOrdersFromJSONTyped(json, false);
}

export function FindOrdersFromJSONTyped(json: any, ignoreDiscriminator: boolean): FindOrders {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'orderType': !exists(json, 'orderType') ? undefined : OrderTypeFromJSON(json['orderType']),
        'page': !exists(json, 'page') ? undefined : json['page'],
        'pageSize': !exists(json, 'pageSize') ? undefined : json['pageSize'],
    };
}

export function FindOrdersToJSON(value?: FindOrders | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'orderType': OrderTypeToJSON(value.orderType),
        'page': value.page,
        'pageSize': value.pageSize,
    };
}


